# Generated by Django 4.2.2 on 2023-06-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_alter_clientes_direccion_alter_clientes_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='seccion',
            field=models.CharField(max_length=30, verbose_name='Sección'),
        ),
    ]
